__Basic Operations on Arrays__

In [ ]:
# Arithmetic operations
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])
#addition
print(a+b)
#subtraction
print(a-b)
#division
print(a/b)
#multiplication
print(a*b)
#modulo
print(a%b)
#exponentiation
print(a**b)
#matrix multiplication
c=np.array([[1,2],[3,4]])
d=np.array([[5,6],[7,8]])
print(np.dot(c,d))
#trigono functions
trig = np.array([0,15,30,60])
#degree to radians
trig1 = np.deg2rad(trig)

#converting the degree values to radians
print("Sin. :", np.sin(trig1))
print("Cos. :", np.cos(trig1))
#log functions
print(np.log(a))
print(np.log10(a))
# #bitwise operations
# bit1 = np.array[(1,2,3,4), dtype=np.unit8]
# bit2 = np.array[(1,2,3,4)]
# print("Bitwise and : ", np.bitwise_and(bit1,bit2))
# print("Bitwise or : ", np.bitwise_or(bit1,bit2))

[ 4  6  8 10 12]
[-2 -2 -2 -2 -2]
[0.33333333 0.5        0.6        0.66666667 0.71428571]
[ 3  8 15 24 35]
[1 2 3 4 5]
[    1    16   243  4096 78125]
[[19 22]
 [43 50]]
Sin. : [0.         0.25881905 0.5        0.8660254 ]
Cos. : [1.         0.96592583 0.8660254  0.5       ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]


TypeError: 'builtin_function_or_method' object is not subscriptable

In [4]:
#comparison operations
print(a==b)
print(a>b)
print(a<b)
print(a!=b)
print(a>=b)
print(a<=b)

[False False False False False]
[False False False False False]
[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]


In [6]:
#aggregation functions

#sum
print(np.sum(a))
#mean
print(np.mean(a))
#median
print(np.median(a))
#std deviation
print(np.std(a))
#variance
print(np.var(a))
#maximum
print(np.amax(a))
#minimum
print(np.amin(a))

15
3.0
3.0
1.4142135623730951
2.0
5
1


In [7]:
#sorting operaitons
print(np.sort(b))

[3 4 5 6 7]


In [8]:
print(np.sort(b)[::-1])

[7 6 5 4 3]
