In [2]:
import numpy as np
#converting python list to numpy array
list1 = [1,2,3,4,5]
array1 = np.array(list1)
print(array1)
#converting tuple to numpy
tuple1 = (1,2,3,4,5)
arr = np.array(tuple1)
print(arr)
# creating 2d array
# a list of lists
array2 = np.array(([5,7],[6,8]))
print(array2)
# array3 = np.array([([1,2],[3,4]),([5,6][7,8])])
# print(array3)

[1 2 3 4 5]
[1 2 3 4 5]
[[5 7]
 [6 8]]


In [ ]:
#creating multi-dimensional arrays using array creation functions

#1d array
#np.arange(1st number, last number, space) or np.arange(range)
#np.linspace
array4 = np.arange(2,10,0.5)

print(array4)

[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval

In [5]:
np.linspace(2.0, 3.0, num=5)


array([2.  , 2.25, 2.5 , 2.75, 3.  ])

Besides creating an array from a sequence of elements, we can easily create an array filled with 0’s using np.zeros:

In [7]:
np.zeros(2)

array([0., 0.])

Or an array filled with 1’s:

In [8]:
np.ones(2)

array([1., 1.])

Or even an empty array! The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [9]:
np.empty(2) 

array([1., 1.])

__Specifying your data type__

While the default data type is floating point (<mark>np.float64</mark>), you can explicitly specify which data type you want using the <mark>dtype</mark> keyword.

In [10]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [11]:
#2d array
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])